// Aqaray automated daily backup: pulls all data from Supabase and uploads
// an Excel backup file (in the same format the app's "Restore from Backup"
// feature expects) to Dropbox.

const XLSX = require("xlsx");

const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const DROPBOX_APP_KEY = process.env.DROPBOX_APP_KEY;
const DROPBOX_APP_SECRET = process.env.DROPBOX_APP_SECRET;
const DROPBOX_REFRESH_TOKEN = process.env.DROPBOX_REFRESH_TOKEN;

// Mirrors the toJs() mappings used inside the Aqaray app itself, so the
// resulting file's sheet/column names exactly match what "Restore from
// Backup" inside the app expects.
const TABLES = {
  users: { table: "app_users", toJs: (r) => ({ id: r.id, name: r.name, pin: r.pin, role: r.role, authUserId: r.auth_user_id }) },
  properties: { table: "properties", toJs: (r) => ({ id: r.id, buildingName: r.building_name, buildingNo: r.building_no, roadNo: r.road_no, blockNo: r.block_no, country: r.country, region: r.region, ownerName: r.owner_name }) },
  units: { table: "units", toJs: (r) => ({ id: r.id, propertyId: r.property_id, unitNo: r.unit_no, unitType: r.unit_type, status: r.status }) },
  tenants: { table: "tenants", toJs: (r) => ({ id: r.id, name: r.name, nationality: r.nationality, passportNo: r.passport_no, idNo: r.id_no, phone: r.phone, email: r.email }) },
  contracts: { table: "contracts", toJs: (r) => ({ id: r.id, unitId: r.unit_id, tenantId: r.tenant_id, startDate: r.start_date, endDate: r.end_date, monthlyRent: r.monthly_rent, depositAmount: r.deposit_amount, electricityLimit: r.electricity_limit, status: r.status, renewedToId: r.renewed_to_id, terminationReason: r.termination_reason, terminationDate: r.termination_date, hasFile: r.has_file, createdBy: r.created_by, contractNo: r.contract_no, openingElecBalance: r.opening_elec_balance }) },
  revenues: { table: "revenues", toJs: (r) => ({ id: r.id, type: r.type, contractId: r.contract_id, propertyId: r.property_id, unitId: r.unit_id, category: r.category, month: r.month, amount: r.amount, date: r.date, paymentMethod: r.payment_method, notes: r.notes, status: r.status, addedBy: r.added_by, docNo: r.doc_no }) },
  expenses: { table: "expenses", toJs: (r) => ({ id: r.id, propertyId: r.property_id, unitId: r.unit_id, category: r.category, amount: r.amount, date: r.date, paymentMethod: r.payment_method, notes: r.notes, addedBy: r.added_by, autoGenerated: r.auto_generated, relatedElectricitySettlementId: r.related_electricity_settlement_id, docNo: r.doc_no }) },
  elecSettlements: { table: "elec_settlements", toJs: (r) => ({ id: r.id, contractId: r.contract_id, month: r.month, billAmount: r.bill_amount, limit: r.limit_amount, chargeTenant: r.charge_tenant, status: r.status, date: r.date, addedBy: r.added_by, docNo: r.doc_no }) },
  depositSettlements: { table: "deposit_settlements", toJs: (r) => ({ id: r.id, contractId: r.contract_id, date: r.date, depositAmount: r.deposit_amount, returnedAmount: r.returned_amount, deductedAmount: r.deducted_amount, deductionReason: r.deduction_reason, method: r.method, docNo: r.doc_no }) },
  templates: { table: "templates", toJs: (r) => ({ id: r.id, docType: r.doc_type, name: r.name, fields: r.fields, imageData: r.image_data }) },
  companyInfo: { table: "company_info", toJs: (r) => ({ id: r.id, companyName: r.company_name, logoData: r.logo_data, bankName: r.bank_name, iban: r.iban, accountHolder: r.account_holder, swiftBic: r.swift_bic }) },
};

async function fetchTable(tableName) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${tableName}?select=*`, {
    headers: {
      apikey: SERVICE_ROLE_KEY,
      Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
    },
  });
  if (!res.ok) throw new Error(`Failed to fetch ${tableName}: ${res.status} ${await res.text()}`);
  return res.json();
}

async function getDropboxAccessToken() {
  const params = new URLSearchParams({
    grant_type: "refresh_token",
    refresh_token: DROPBOX_REFRESH_TOKEN,
    client_id: DROPBOX_APP_KEY,
    client_secret: DROPBOX_APP_SECRET,
  });
  const res = await fetch("https://api.dropbox.com/oauth2/token", { method: "POST", body: params });
  if (!res.ok) throw new Error(`Dropbox token refresh failed: ${res.status} ${await res.text()}`);
  const json = await res.json();
  return json.access_token;
}

async function uploadToDropbox(accessToken, filename, buffer) {
  const res = await fetch("https://content.dropboxapi.com/2/files/upload", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Dropbox-API-Arg": JSON.stringify({
        path: `/${filename}`,
        mode: "overwrite",
        autorename: false,
        mute: true,
      }),
      "Content-Type": "application/octet-stream",
    },
    body: buffer,
  });
  if (!res.ok) throw new Error(`Dropbox upload failed: ${res.status} ${await res.text()}`);
  return res.json();
}

(async () => {
  console.log("Fetching data from Supabase...");
  const wb = XLSX.utils.book_new();

  for (const [sheetName, cfg] of Object.entries(TABLES)) {
    const rawRows = await fetchTable(cfg.table);
    const rows = rawRows.map(cfg.toJs).map((row) => {
      const copy = { ...row };
      Object.keys(copy).forEach((k) => {
        if (copy[k] && typeof copy[k] === "object") copy[k] = JSON.stringify(copy[k]);
      });
      return copy;
    });
    const sheet = XLSX.utils.json_to_sheet(rows.length ? rows : [{}]);
    XLSX.utils.book_append_sheet(wb, sheet, sheetName.slice(0, 31));
    console.log(`  ${sheetName}: ${rows.length} rows`);
  }

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  const today = new Date().toISOString().slice(0, 10);
  const filename = `aqaray_auto_backup_${today}.xlsx`;

  console.log("Getting Dropbox access token...");
  const accessToken = await getDropboxAccessToken();

  console.log(`Uploading ${filename} to Dropbox...`);
  await uploadToDropbox(accessToken, filename, buffer);

  console.log("Backup complete.");
})().catch((err) => {
  console.error("Backup failed:", err);
  process.exit(1);
});
